---
resources:
- name: legacy-tomcat-app
  type: git
  source:
    uri: https://github.com/making/hello-legacy-tomcat-dev.git
- name: legacy-tomcat-cf
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: unit-test
  plan:
  - get: legacy-tomcat-app
    trigger: true
  - task: mvn-test
    config:
      platform: linux
      inputs:
      - name: legacy-tomcat-app
      image_resource:
        type: docker-image
        source:
          repository: nexus.ik.am:18443/maven
          insecure_registries:
          - nexus.ik.am:18443
          username: {{nexus-username}}
          password: {{nexus-password}}
      run:
        path: sh
        args:
        - -c
        - |
          cd legacy-tomcat-app
          mvn test
- name: deploy-to-nexus
  plan:
  - get: legacy-tomcat-app
    trigger: true
    passed:
    - unit-test
  - task: mvn-deploy
    config:
      platform: linux
      inputs:
      - name: legacy-tomcat-app
      outputs:
      - name: output
      image_resource:
        type: docker-image
        source:
          repository: nexus.ik.am:18443/maven
          insecure_registries:
          - nexus.ik.am:18443
          username: {{nexus-username}}
          password: {{nexus-password}}
      run:
        path: sh
        args:
        - -c
        - |
          cd legacy-tomcat-app
          echo "<settings><servers><server><id>private-snapshots</id><username>{{nexus-username}}</username><password>{{nexus-password}}</password></server><server><id>private-releases</id><username>{{nexus-username}}</username><password>{{nexus-password}}</password></server></servers></settings>" > settings.xml
          mvn deploy -s settings.xml
- name: deploy-to-cf
  plan:
  - get: legacy-tomcat-app
    trigger: true
    passed:
    - deploy-to-nexus
  - task: mvn-download
    config:
      platform: linux
      inputs:
      - name: legacy-tomcat-app
      outputs:
      - name: output
      image_resource:
        type: docker-image
        source:
          repository: nexus.ik.am:18443/maven
          insecure_registries:
          - nexus.ik.am:18443
          username: {{nexus-username}}
          password: {{nexus-password}}
      run:
        path: sh
        args:
        - -c
        - |
          cd legacy-tomcat-app
          mvn -f pom-get.xml validate
          mv app.war ../output
  - put: legacy-tomcat-cf
    params:
      manifest: legacy-tomcat-app/manifest.yml
      path: output/app.war